### ISSUE TITLE
create a list of cars page to get an overview of all the cars and select from them to modify them if need be

### ISSUE THREAD

**Issue by DavidLobo757** [DanBerkness/Cars#13]

**Comment by DanBerkness** [comment]
There was a discussion and it was agreed to name the URL "cars".

**Comment by petecarapetyan** [comment]
Probably would need this search or something like it

`populate table with thymeleaf`

https://www.google.com/search?q=populate+table+with+thymeleaf&oq=table+with+thy&aqs=chrome.2.69i57j0i22i30l6j0i10i22i30j0i22i30l2.10056j0j7&sourceid=chrome&ie=UTF-8

**Comment by DanBerkness** [comment]
Cool!
